### ISSUE TITLE
In "Evaluation" tab, need to check if files exist

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#10]
When the path to source text and/or reference text does not exist, the program breaks.

**Traceback:**
Traceback (most recent call last):
  File "main.py", line 944, in _evaluate
    self.evaluation_reference.get_text())
  File "/home/rlafuente/TTT/evaluation.py", line 89, in evaluate
    key = (test,creation_date(test),reference,creation_date(reference), checkbox_indexes_constants[checkbox_index])
  File "/home/rlafuente/TTT/evaluation.py", line 37, in creation_date
    stat = os.stat(path_to_file)
OSError: [Errno 2] No existe el archivo o el directorio: '5e/corpus/translate.en'

Traceback (most recent call last):
  File "main.py", line 944, in _evaluate
    self.evaluation_reference.get_text())
  File "/home/rlafuente/TTT/evaluation.py", line 89, in evaluate
    key = (test,creation_date(test),reference,creation_date(reference), checkbox_indexes_constants[checkbox_index])
  File "/home/rlafuente/TTT/evaluation.py", line 37, in creation_date
    stat = os.stat(path_to_file)
OSError: [Errno 2] No existe el archivo o el directorio: '/home/rlafuente/cor5ource.en'

**Comment by miguelemosreverte** [comment]
Fixed.
