### ISSUE TITLE
Machine translation tab error

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#4]
It is not performing the machine translation.

**Info:**
Traceback (most recent call last):
  File "main.py", line 765, in _machine_translation
    self._has_empty_last_line(in_file):
  File "main.py", line 753, in _has_empty_last_line
    last_line_is_empty = "\n" in (f.readlines()[-1])
IndexError: list index out of range

**Comment by roxana-lafuente** [comment]
This happened when the translation file selected in the "Machine Translation" tab was empty.

**Comment by roxana-lafuente** [comment]
Separated issue in 2 since one part is fixed.
