### ISSUE TITLE
In "Evaluation" tab, start evaluation exception

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#6]
When you do not choose a file but choose (WER, BLEU, PER, HTER, BLEU3GRAM, BLEU4GRAM, GTM) and click on "Start Evaluation" button
**Info:**

Traceback (most recent call last):
  File "main.py", line 941, in _evaluate
    self.evaluation_reference.get_text())
  File "/home/rlafuente/TTT/evaluation.py", line 89, in evaluate
    key = (test,creation_date(test),reference,creation_date(reference), checkbox_indexes_constants[checkbox_index])
  File "/home/rlafuente/TTT/evaluation.py", line 37, in creation_date
    stat = os.stat(path_to_file)
OSError: [Errno 2] No existe el archivo o el directorio: ''

**Comment by miguelemosreverte** [comment]
Solved!
